mindmap
  root(Interests)
    Mathematics
      Category Theory
      Set Theory
      Mathematical Logic
      Graph Theory
    History
      Americas
        USA
        Pre-Columbian
      Europe
      Asia
      Elsewhere
    Prehistory
    Gospel Studies
      Christianity
        Historical Theology
        Ancient Christianity
      Judaism
        Pre-Judaism
        Temple Studies
      Islam
      Other Religions
    Physics & Astronomy
      Quantum Mechanics
      Quantum Field Theory
      Cosmology
    Computation Science
      Decision Theory
      Programming Languages

